### ISSUE TITLE
Implement Russian-style upright Integral symbols

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [stipub/stixfonts#105] opened 2018-06-05 14:59 UTC
In [Wikipedia](https://en.wikipedia.org/wiki/Integral_symbol) I found another form of Integral symbol which leans to the left. I suggest adding a style set to make it available.

**Comment by davidmjones** [comment] 2018-06-06 13:31
Thanks for the suggestion.  We'll take it under consideration, although in the absence of active interest from users who want to use these forms, it will probably be low priority.

**Comment by tiroj** [comment] 2021-03-22 20:15
Closing for now. Can reconsider if the issue is raised again.

**Closed by tiroj** 2021-03-22 20:15 UTC
